name: duomorphsim
description: this package help you to give glassomorphic+ neomrphic both effects to a container (at a time).
version: 0.0.1
homepage: "https://www.instagram.com/theflutterfoundry"
repository: "https://github.com/RitickSaha/glassmorphism"
issue_tracker: "https://github.com/RitickSaha/glassmorphism/issues"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

